### ISSUE TITLE
Flashing the original chip

### ISSUE THREAD

**Issue by sebastianrakel** [dckiller51/esphome-yeelight-led-screen-light-bar#4]
Not a real issue but a question.

Die you manage to flash the original chip with a new firmware or did you replaced it with an d1-mini?

If you manage to flash it, what was the baud rate of the original chip and how did you flash it?

best regards
Sebastian

**Comment by dckiller51** [comment]
Hello, I flashed the original chip. It flashes the same way as the others.

**Comment by sebastianrakel** [comment]
Okay, do you have also reboot problems? if i turn both lights on, it will reboot

**Comment by dckiller51** [comment]
no worries you can turn on the 2 lights at the same time.

**Comment by sebastianrakel** [comment]
perfect, thank you :)
